### ISSUE TITLE
Schema 

### ISSUE THREAD

**Issue by PLUCS2** [syldysnya/OpenDnDTable#2]
- [x] Address and Phone number on the Players table will be part of the BONUS when you go to fill out a users profile - initially you will just need their city 
- [x] You should have an index on `city_id` on the Players table since it is a foreign key
- [x] What is `Sessions` - it looks like something that is not available as part of Open Table's functionality. There is an option of Reservation Details on Open Table, so you can adapt the Sessions to be reservation details (they should therefore be attached to a reservation via a reservation_id) - we can chat more about this if this does not make sense 
- [x] What is Points? - if these are like the points that users get on Open Table that looks good 

Excellent work Sy! I am really excited for this project - let me know if you have any questions

**Comment by syldysnya** [comment]
I renamed `sessions` to `dnd_campaigns`, so it wont be confusing with sessions of user. 
`dnd_campaigns` is like `menu and cuisine` in OpenTable. Players will be able to find a `game_place` by choosing a dnd_campaign. And in game_place's show page I will be able to display dnd_campaigns like restaurants do in a section 'popular dishes'. If it makes sense, if not I can rethink the whole concept of `dnd_campaigns` table.

Fixed all other issues, thanks!

**Comment by PLUCS2** [comment]
How are dnd_campaigns connected to the games? i.e. how does this connect to open table having cuisines that connect to restaurants? (right now those connections in relation to OpenTable are not clear) 

As this is unnecessary for auth lets talk through it once you reach that point in your project :)

**Comment by syldysnya** [comment]
Dnd_campaigns are like genre of movies, or cuisines of restaurants. When a user search them can choose the genre of the game (ex, epic campaign, short session, dungeon crawling, etc). OpenTable has two tables (for cuisine, and menus), but in my clone I'll put it under one table called 'dnd_campaign'. So my search page will have more options/variety to filter, and my game place page will have more information and won't look empty.

I put screenshots from Open Table where I will use dnd_campaigns instead.
![Screen Shot 2021-05-09 at 6 10 43 PM](https://user-images.githubusercontent.com/78821780/117588614-65b70700-b0f2-11eb-8613-5440c8ac2588.png)
![Screen Shot 2021-05-09 at 6 11 02 PM](https://user-images.githubusercontent.com/78821780/117588626-897a4d00-b0f2-11eb-8456-5a429ed4d273.png)
